"""
OmniBrain — AI Disclosure (EU AI Act Compliance)

Implements three disclosure mechanisms as required by the manifesto:
1. Email drafts: configurable footer declaring AI origin
2. Chat responses: metadata flag for frontend badge rendering
3. Briefings: header with generation timestamp and disclosure
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger("omnibrain.disclosure")

# ═══════════════════════════════════════════════════════════════════════════
# Defaults — user-configurable from Settings
# ═══════════════════════════════════════════════════════════════════════════

DEFAULT_EMAIL_FOOTER = (
    "---\n"
    "This message was drafted by OmniBrain on behalf of {user_name}."
)

DEFAULT_BRIEFING_HEADER = (
    "Generated by OmniBrain · {date} · Not verified by human"
)


# ═══════════════════════════════════════════════════════════════════════════
# Disclosure helpers
# ═══════════════════════════════════════════════════════════════════════════


def email_disclosure_footer(
    user_name: str = "the user",
    custom_text: str = "",
    enabled: bool = True,
) -> str:
    """Return the AI disclosure footer for email drafts.

    Returns empty string if disabled.
    """
    if not enabled:
        return ""
    template = custom_text or DEFAULT_EMAIL_FOOTER
    return template.format(user_name=user_name)


def briefing_disclosure_header(
    date: str = "",
    custom_text: str = "",
) -> str:
    """Return the AI disclosure header for briefings."""
    template = custom_text or DEFAULT_BRIEFING_HEADER
    return template.format(date=date)


def chat_disclosure_metadata() -> dict[str, Any]:
    """Return metadata dict to include in SSE frames for AI-generated content.

    The frontend renders a discrete badge from this flag.
    """
    return {
        "ai_generated": True,
        "disclosure": "This response was generated by AI",
    }


def apply_email_disclosure(
    draft: str,
    user_name: str = "the user",
    db: Any = None,
) -> str:
    """Append AI disclosure footer to an email draft.

    Reads user preferences for custom footer text and enable/disable.
    """
    enabled = True
    custom_text = ""

    if db:
        try:
            pref = db.get_preference("ai_disclosure_email_enabled")
            if pref is not None:
                enabled = str(pref).lower() not in ("false", "0", "no", "off")

            custom = db.get_preference("ai_disclosure_email_text")
            if custom:
                custom_text = str(custom)

            name_pref = db.get_preference("user_name")
            if name_pref:
                user_name = str(name_pref)
        except Exception as e:
            logger.debug(f"Could not read disclosure prefs: {e}")

    footer = email_disclosure_footer(
        user_name=user_name,
        custom_text=custom_text,
        enabled=enabled,
    )

    if footer:
        return f"{draft}\n\n{footer}"
    return draft
